[package]
name = "sucds-bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sucds = { path = ".." }
rand = "0.8.4"
rand_chacha = "0.3.1"
bincode = "1.3.3"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "timing_rank"
harness = false

[[bench]]
name = "timing_select"
harness = false

[[bin]]
name = "memory"
path = "src/memory.rs"